# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <link rel=\"icon\" type=\"image/x-icon\" href=\"static/favicon.png\">
    <link rel=\"stylesheet\" href=\"static/mvp.css\" />
    <link rel=\"stylesheet\" href=\"static/custom.css\" />
    <title>PicoPower</title>
  </head>
  <body>
    <header>
      <nav>
        <a href=\"/\" id=\"name\">PicoPower</a>
        <ul>
          <li><a href=\"/install\">Settings</a></li>
        </ul>
      </nav>
    </header>
    <main>
      <section>
        <aside>
            <h2>Rebooting...</h2>
            <h2><center><span id=\"countdown\">15</span></center></h2>           
        </aside>
      </section>
      <script type=\"text/javascript\">
		var timeLeft = 15;
		var countdown = setInterval(function()"""
    yield """{
			timeLeft--;
			document.getElementById(\"countdown\").textContent = timeLeft;
			if(timeLeft <= 0)
				clearInterval(countdown);
		}, 1000);

		setTimeout(function()"""
    yield """{
			window.location.href = \"/\";
		}, 15000);
	</script>
    </main>
    <footer id=\"footer\">
      <hr />
      <p>
        <small>© <a href=\"https://www.drebollo.com\">drebollo.com</a></small>
      </p>
    </footer>
  </body>
</html>

"""
